### ISSUE TITLE
Assignee update problem

### ISSUE THREAD

**Issue by adrien-delhorme** [kapt-labs/bugboard#9]
It seems that the `updatebbdb` script does not correctly update the tasks assignees:
- on bugherd, this task is assigned to Saad (https://www.bugherd.com/projects/182254/tasks/14)
- on bugboard, no one is assigned

**Comment by corentinbettiol** [comment]
See [this comment](https://github.com/kapt-labs/bugboard/issues/5#issuecomment-559026092) for more information on why assignees aren't updated.
Closing this issue since I re-opened #5 .
